language: python
sudo : false
addons:
  apt:
    packages:
    - poppler-utils
python:
  - "2.7"
  - "3.4"
notifications:
  email: false
before_install:
  - pip install pip --upgrade
  - pip install bibtexparser
  - pip install six
  - pip install crossrefapi
  - pip install fuzzywuzzy
  - pip install unidecode
  - pip install scholarly
# test coverage
#  - pip install tox
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - python setup.py install

script: py.test -xv --cov papers.bib tests

after-success: coveralls
